# Generated by Django 4.2.8 on 2024-05-18 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
