# Generated by Django 4.2.8 on 2024-05-22 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth', models.DateField(blank=True, null=True)),
                ('household_size', models.PositiveIntegerField()),
                ('marital_status', models.CharField(choices=[('single', '미혼'), ('married', '기혼')], max_length=10)),
                ('has_children', models.BooleanField(blank=True, null=True)),
                ('income', models.DecimalField(decimal_places=1, max_digits=20)),
                ('savings', models.ManyToManyField(to='portfolio.savingoption')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
